export const doctorSpecializations = [
    { name: "Anesthesiology", description: "Focuses on pain relief and maintaining vital functions during surgery and procedures." },
    { name: "Cardiology", description: "Deals with diseases and disorders of the heart and blood vessels." },
    { name: "Dermatology", description: "Diagnosis and treatment of skin, hair, and nail conditions." },
    { name: "Emergency Medicine", description: "Provides immediate care for acute illnesses or injuries." },
    { name: "Endocrinology", description: "Manages hormone-related disorders like diabetes and thyroid diseases." },
    { name: "Family Medicine", description: "Offers comprehensive, continuous healthcare for individuals and families." },
    { name: "Gastroenterology", description: "Treats disorders of the digestive system and related organs." },
    { name: "General Surgery", description: "Involves surgical treatment of a wide range of diseases, often abdominal." },
    { name: "Geriatrics", description: "Focuses on healthcare of elderly people and age-related diseases." },
    { name: "Hematology", description: "Deals with blood disorders, including anemia, leukemia, and clotting disorders." },
    { name: "Infectious Disease", description: "Specializes in diagnosis and management of infections caused by bacteria, viruses, fungi, or parasites." },
    { name: "Internal Medicine", description: "Provides comprehensive care for adults, focusing on prevention, diagnosis, and treatment of chronic conditions." },
    { name: "Nephrology", description: "Treats kidney diseases and disorders affecting kidney function." },
    { name: "Neurology", description: "Deals with diseases of the nervous system — brain, spinal cord, and nerves." },
    { name: "Neurosurgery", description: "Performs surgical treatment of disorders of the brain, spinal cord, and nervous system." },
    { name: "Obstetrics and Gynecology (OB/GYN)", description: "Cares for women’s reproductive health, pregnancy, and childbirth." },
    { name: "Oncology", description: "Focuses on the diagnosis and treatment of cancer." },
    { name: "Ophthalmology", description: "Deals with diseases and surgery of the eyes and visual system." },
    { name: "Orthopedic Surgery", description: "Treats disorders of bones, joints, ligaments, tendons, and muscles." },
    { name: "Otolaryngology (ENT)", description: "Treats conditions of the ear, nose, and throat." },
    { name: "Pathology", description: "Studies diseases through examination of organs, tissues, and bodily fluids." },
    { name: "Pediatrics", description: "Provides medical care for infants, children, and adolescents." },
    { name: "Physical Medicine & Rehabilitation", description: "Helps restore function to people with physical impairments or disabilities." },
    { name: "Plastic and Reconstructive Surgery", description: "Performs cosmetic or reconstructive surgery to restore appearance or function." },
    { name: "Psychiatry", description: "Focuses on mental health, including depression, anxiety, and other psychological disorders." },
    { name: "Pulmonology", description: "Treats diseases of the lungs and respiratory system." },
    { name: "Radiology", description: "Uses imaging techniques (X-rays, MRI, CT scans) to diagnose and treat diseases." },
    { name: "Rheumatology", description: "Manages autoimmune and musculoskeletal disorders like arthritis and lupus." },
    { name: "Urology", description: "Treats disorders of the urinary tract and male reproductive organs." },
    { name: "Allergy and Immunology", description: "Diagnoses and treats allergic conditions and immune system disorders." },
    { name: "Sports Medicine", description: "Focuses on physical fitness, sports injury prevention, and rehabilitation." },
    { name: "Palliative Medicine", description: "Provides comfort and quality of life for patients with serious or terminal illnesses." },
    { name: "Preventive Medicine", description: "Promotes health and wellness through prevention and lifestyle improvement." },
    { name: "Occupational Medicine", description: "Focuses on health and safety in the workplace." },
    { name: "Nuclear Medicine", description: "Uses radioactive substances to diagnose and treat diseases." },
    { name: "Genetic Medicine", description: "Deals with genetic disorders and counseling for inherited diseases." },
    { name: "Critical Care Medicine", description: "Manages life-threatening conditions in intensive care units." },
    { name: "Pain Medicine", description: "Specializes in the evaluation and management of chronic pain." },
    { name: "Public Health", description: "Focuses on population health, disease prevention, and health policy." },
    { name: "Vascular Surgery", description: "Treats diseases of the blood vessels, such as aneurysms and varicose veins." },
    { name: "Thoracic Surgery", description: "Performs surgery on organs in the chest, including lungs and esophagus." },
    { name: "Forensic Medicine", description: "Applies medical knowledge in legal investigations and cases." },
    { name: "Dental Surgery", description: "Cares for teeth, gums, and mouth; includes oral and maxillofacial surgery." },
    { name: "Neonatology", description: "Provides medical care to newborn infants, especially premature or ill babies." }
];


export const alloHealthClinicLocation = [
    "Mumbai", "Pune", "Ranchi", "Hyderabad", "Mysore", "Bangalore", "Chennai"
];